### ISSUE TITLE
Use RDS session token instead of secrets manager

### ISSUE THREAD

**Issue by bick4ord** [a-h/go-sql-driver-rds-credentials#2]
Hi!  I was able to get your code up and running pretty quickly, but I didn't want to use the Secrets Manager integration.  I forked and got an implementation working that uses the AWS RDS lib to generate a short-lived token for authentication.  I didn't bother with a formal PR since I didn't bother doing a clean swap (lots of cruft left), and I didn't bother with additional tests.  Feel free to close the issue, just wanted to make you aware of it:

https://github.com/bick4ord/go-sql-driver-rds-credentials/pull/1

edit:
for clarification, I got the AWS session using a callback function.  This allows optionally doing an assume role from the client, without dealing with the mess of passing that configuration down.

**Comment by a-h** [comment]
Thanks. Glad it's working for you.

The bottom of this doc had a bit of frightening information which put me off using IAM, even though it's a nicer solution. While I'm not likely to see 256 connections per second to my databases, the text didn't inspire confidence. :)

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html

From the docs:

* Use IAM database authentication as a mechanism for temporary, personal access to databases.
* Use IAM database authentication only for workloads that can be easily retried.
* Don't use IAM database authentication if your application requires more than 256 new connections per second.
